version: '2'

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "7777:7777"   # Dashboard Traefik (assure-toi que 7777 est bien celui que tu veux)
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./certs/:/var/traefik/certs/:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
    networks:
      webTraefik:  
networks:
  webTraefik:
    external: true