name: Deploy Traefik

on:
  push:
    branches:
      - main  # Déploie Traefik à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Traefik on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          set -e  # Stop if an error occurs

          # Aller dans le dossier de Traefik (ou le créer)
          mkdir -p /home/traefik && cd /home/traefik

          # Télécharger le dernier docker-compose.yml
          curl -o docker-compose.yml https://raw.githubusercontent.com/https://github.com/j-b974/Treafik/main/docker-compose.yml

          # Vérifier la config
          docker compose config

          # Arrêter et supprimer le service Traefik
          docker compose down

          # Mettre à jour les images Docker
          docker compose pull

          # Relancer Traefik
          docker compose up -d

          echo "✅ Traefik redémarré avec succès !"
          EOF
