name: Deploy Traefik

on:
  push:
    branches:
      - main  # Déploie Traefik à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: acceVPN
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Debug VPS_IP
        run: echo "VPS_IP=${{ secrets.VPS_IP }}"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Traefik on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_IP }} "
            if [-d /home/traefik]; then
              cd /home/traefik && git pull origin main
            else
              git clone depth==1 https://github.com/j-b974/Treafik.git
            fi
          "
      - name: Redemarre Traefik avec Docker
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_IP }}"
            cd /home/traefik
            echo "CF_DNS_API_TOKEN=${{ secrets.API_KEY_CLOUDFLARE}}" >> .env
            docker-compose down
            docker-compose up -d
          "